version: '3.9'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.8.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.8.0
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  postgres-orders:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: orders
    ports:
      - "5433:5432"

  postgres-payments:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: payments
    ports:
      - "5434:5432"

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: shop-app-gateway
    ports:
      - "8080:8080"
    depends_on:
      - orders-service
      - payments-service

  orders-service:
    build:
      context: ./orders-service
      dockerfile: Dockerfile
    container_name: shop-app-orders-service
    ports:
      - "8081:8081"
    depends_on:
      - kafka
      - postgres-orders

  payments-service:
    build:
      context: ./payments-service
      dockerfile: Dockerfile
    container_name: shop-app-payments-service
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - postgres-payments

